### ISSUE TITLE
Depends list issues

### ISSUE THREAD

**Issue by dewhisna** [snatella/amarok-eoan-builder#1]
First off, I want to say `Thank You` for putting this package generator together!

I am installing this on Xubuntu 20.04 and hit a few issues with your generated `amarok` package.  First off, `python-minimal` is listed in your `DEBIAN/control` file, but there is no such package.  There are `python2-minimal`, `python2.7-minimal`, `python3-minimal`, and `python3.8-minimal` packages.  So, I assume your entry just needs to be changed to `python3-minimal`, since it looks like it uses python3.

Next, after installing this package, I was still missing `libkf5kiofilewidgets5` and `liblastfm5-1` and had to install them manually to get it to launch, so looks like they need to be added to your `Depends` list in the `DEBIAN/control` file.

**Comment by snatella** [comment]
@dewhisna apologies, I had locally made the `python3-minimal` change and didn't commit it!

These all should be fixed in f1d544c.

And it's great to hear from someone using it! I'm closing this as fixed for now, please re-open if I've hamfisted something ;-)

**Comment by dewhisna** [comment]
@snatella no problems.  Thanks for fixing it.

After building and installing the package from here (which worked great except for those few dependencies), I've since learned that Pedro de Carvalho Gomes (apparently one of the developers of Amarok) has a PPA for the in-progress port of Amarok to Qt5 at: https://launchpad.net/~pgomes/+archive/ubuntu/amarok/+index which may ultimately obsolete this repo.

**Comment by snatella** [comment]
@dewhisna definitely a proper PPA is the way forwards. This was my way of hacking around the lack of amarok inclusion in ubuntu, so it becoming obsolete at some point was (hopefully!) a given.
